### ISSUE TITLE
【技术问题】增加Labels的按钮在哪里？可否截图发到微信群？@zhangshiying

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [runwithcc/CTTEC#1]
【技术问题】增加Labels的按钮在哪里？可否截图发到微信群？@zhangshiying

**Comment by Wangjunyu** [comment]
好问题，我也没有找到Lables的添加位置。New issue里也没有

**Comment by runwithcc** [comment]
每一个Issues右侧的侧边栏里面都有，分别是：标签、里程碑、合作者、通知等相关信息。

**Comment by runwithcc** [comment]
问题解决，Issue Close

**Comment by Wangjunyu** [comment]
@zhangshiyinrunwithcc  我在自己的项目的issue测试了一下，只有拥有者才能添加标签，我们没有权限的。
