### ISSUE TITLE
电脑水平不高的人能玩得转吗？

### ISSUE THREAD

**Issue by beat5912** [runwithcc/CTTEC#2]
好像要技术控，经常玩电脑的人对这个能很快上手。我是电脑技术小白。跟着永澄老师和各位大牛学习！

**Comment by runwithcc** [comment]
本活动的目标是让大家看到我的课程记录和最后的展示内容，这个目标能够达成就可以了。如果非要考虑也拥有和我一样的体系，那需要参加前置活动，就是像极客一样写作，否则无法搞定。

回答结束，close
